[[UNRESOLVED_FN]]
id = "CODEWARE_10104"
line_contains = "UTF8StrLower"
message = "Install Codeware 1.1.5 or higher"

[[UNRESOLVED_METHOD]]
id = "CODEWARE_10104"
line_contains = "GetClosestControllerByType"
message = "Install Codeware 1.1.5 or higher"
