[[UNRESOLVED_FN]]
id = "CODEWARE_10401"
line_contains = "UTF8StrLower"
message = "Install Codeware 1.4.1 or higher"

[[UNRESOLVED_METHOD]]
id = "CODEWARE_10401"
line_contains = "GetClosestControllerByType"
message = "Install Codeware 1.4.1 or higher"
